workflows:
  build-android:
    name: Build React Web to Android APK
    max_build_duration: 60
    environment:
      node: stable
      vars:
        NODE_ENV: production
        VITE_API_URL: $VITE_API_URL
        VITE_API_URL_IMAGE: $VITE_API_URL_IMAGE
    scripts:
      - name: Install dependencies
        script: npm install --legacy-peer-deps
      - name: Build React Web
        script: npm run build
      - name: Copy React Web to Android
        script: npx cap copy android
      - name: Build APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
